[package]
name = "lll-sample"
version = "0.1.0"
authors = ["Steven Holtzen <sholtzen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.18"
dimacs = "0.2.0"
maplit = "1.0.1"
bitvec = "0.17.4"

